language: go

go:
  - 1.11.x
  - 1.12.x
  - master

before_install:
  - go get -v .

install:
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
